# Generated by Django 5.1.6 on 2025-03-11 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'unique_together': {('entity_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервисная компания',
                'verbose_name_plural': 'Сервисные компании',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('engine_serial_number', models.CharField(max_length=255)),
                ('transmission_serial_number', models.CharField(max_length=255)),
                ('axle_serial_number', models.CharField(max_length=255)),
                ('steering_axle_serial_number', models.CharField(max_length=255)),
                ('contract_number_data', models.CharField(max_length=255)),
                ('shipment_date', models.DateField()),
                ('recipient', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('configuration', models.TextField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='mysilant.client')),
                ('axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axles_model', to='mysilant.reference')),
                ('engine_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engines_model', to='mysilant.reference')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model', to='mysilant.reference')),
                ('steering_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steering_axles_model', to='mysilant.reference')),
                ('transmission_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissions_model', to='mysilant.reference')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='mysilant.serviceorganization')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_date', models.DateField()),
                ('operating_hours', models.FloatField()),
                ('failure_description', models.TextField()),
                ('used_spare_parts', models.TextField()),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('downtime_duration', models.DurationField(blank=True, null=True)),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='mysilant.machine')),
                ('failure_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_nodes', to='mysilant.reference')),
                ('recovery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='mysilant.reference')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='mysilant.serviceorganization')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
        ),
        migrations.CreateModel(
            name='TechnicalMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.FloatField()),
                ('order_number', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='mysilant.machine')),
                ('service_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performing_services', to='mysilant.serviceorganization')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='mysilant.reference')),
            ],
        ),
    ]
