# Generated by Django 5.1.6 on 2025-03-11 08:51

from django.db import migrations

def create_self_service_organization(apps, schema_editor):
    # Получаем модель ServiceOrganization
    ServiceOrganization = apps.get_model('mysilant', 'ServiceOrganization')
    
    # Создаем запись "Самостоятельно", если её ещё нет
    ServiceOrganization.objects.get_or_create(
        name="Самостоятельно",
        defaults={'description': 'Клиент выполняет обслуживание самостоятельно'}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('mysilant', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_self_service_organization),
    ]
