# Generated by Django 5.1.6 on 2025-03-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mysilant', '0003_entity_alter_technicalmaintenance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='downtime_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='failure_description',
            field=models.TextField(verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='failure_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_nodes', to='mysilant.reference', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim', to='mysilant.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='operating_hours',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='recovery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='recovery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='mysilant.reference', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='rejection_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim', to='mysilant.serviceorganization', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='used_spare_parts',
            field=models.TextField(verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='axle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='axles_model', to='mysilant.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='axle_serial_number',
            field=models.CharField(max_length=255, verbose_name='Зав.№ ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='mysilant.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='configuration',
            field=models.TextField(verbose_name='Комплектация (доп.опции)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='contract_number_data',
            field=models.CharField(max_length=255, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engines_model', to='mysilant.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_serial_number',
            field=models.CharField(max_length=255, verbose_name='Зав.№ двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines_model', to='mysilant.reference', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='recipient',
            field=models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Зав.№ машины'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='mysilant.serviceorganization', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipment_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steering_axles_model', to='mysilant.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_serial_number',
            field=models.CharField(max_length=255, verbose_name='Зав.№ управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transmissions_model', to='mysilant.reference', verbose_name='Модель трансиссии(производитель, артикул)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_serial_number',
            field=models.CharField(max_length=255, verbose_name='Зав.№ трансмиссии'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to='mysilant.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='maintenance_date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='operating_hours',
            field=models.FloatField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performing_services', to='mysilant.serviceorganization', verbose_name='Сервисная организация'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='mysilant.reference', verbose_name='Вид ТО'),
        ),
    ]
