# Generated by Django 5.1.6 on 2025-03-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilant', '0005_remove_technicalmaintenance_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='mysilant.serviceorganization', verbose_name='Организация, проводившая ТО'),
        ),
    ]
