# Generated by Django 5.1.6 on 2025-03-29 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysilant', '0007_client_created_at_client_name_manager_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='mysilant.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_claims', to='mysilant.serviceorganization', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='mysilant.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='technicalmaintenance',
            name='service_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenances', to='mysilant.serviceorganization', verbose_name='Сервисная организация'),
        ),
    ]
